[package]
name = "otter_sat"
version = "0.1.0"
edition = "2021"

[features]
time = []
extra_stats = []

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
log = { version = "0.4.22", features = ["max_level_debug", "release_max_level_debug"] }
log4rs = { version = "1.3.0" }
slotmap = { version = "1.0" }

[profile.profiling]
inherits = "release"
debug = true
