[workspace]
resolver = "2"
members = [
   "otter_lib",
   "otter_cli",
   "otter_tests",
]

[profile.profiling]
codegen-units = 1
debug = true
inherits = "release"
lto = true

[profile.redline]
codegen-units = 1
debug = false
inherits = "release"
lto = true
panic = "abort"
