[package]
name = "otter_sat"
version = "0.1.0"
edition = "2021"

[features]
jemalloc = [ "dep:tikv-jemallocator" ]

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap-markdown = "0.1.4"
crossterm = "0.28.1"
log = { version = "0.4.22", features = ["max_level_debug", "release_max_level_off"] }
log4rs = { version = "1.3.0" }
petgraph = "0.6.5"
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
slotmap = { version = "1.0" }
tikv-jemallocator = { version = "0.6", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[profile.profiling]
debug = true
inherits = "release"

[profile.redline]
codegen-units = 1
debug = false
inherits = "release"
lto = true
panic = "abort"
