[package]
name = "otter_sat"
version = "0.1.0"
edition = "2021"

[features]
time = []
extra_stats = []

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
log = { version = "0.4.22", features = ["max_level_debug", "release_max_level_off"] }
log4rs = { version = "1.3.0" }
petgraph = "0.6.5"
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
slotmap = { version = "1.0" }

[profile.profiling]
inherits = "release"
panic = "unwind"
debug = true

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
