[package]
name = "vsat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
log = { version = "0.4.22" }
log4rs = { version = "1.3.0" }
petgraph = "0.6.5"
