appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console

  graph_appender:
    kind: console
    encoder:
      pattern: "{d(%H:%M:%S)} | {({l}):5.5} | {f}:{L}\t {m}{n}"

  forget_appender:
    kind: console
    encoder:
      pattern: "{d(%H:%M:%S)} | {({l}):5.5} | {f}:{L}\t {m}{n}"

root:
  level: off
  appenders:
    - stdout

loggers:
  graph:
    level: off
    appenders:
    - graph_appender
    additive: false

  forget:
    level: on
    appenders:
    - forget_appender
    additive: false