appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console

  graph_appender:
    kind: console
    encoder:
      pattern: "{d(%H:%M:%S)} | {({l}):5.5} | {f}:{L}\t {m}{n}"

root:
  level: warn
  appenders:
    - stdout

loggers:
  graph:
    level: warn
    appenders:
    - graph_appender
    additive: false
